#!/usr/bin/ruby
$:.push(File.join(File.dirname(__FILE__), '../lib'))

require 'fcm-agent-tools'
require 'fileutils'

PASSWD = '/etc/passwd'
OWNER = 'root'
GROUP = 'root'
PERM = 0444

f = FCM::Agent.new

begin
  # Don't do anything if the files are the same
  unless f.diff(PASSWD, f.filedata)
    return 0
  end
  # Bail unless root is there
  unless f.filedata.match('^root:')
    return 1
  end
  begin
    f.install_file(PASSWD, OWNER, GROUP, PERM)
    Kernel.system("pwconv")
  rescue => x
    raise "Failed to install passwd file: #{x}"
  end
rescue => x
  puts "General passwd file exception: #{x}"
end

